config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :monsters
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :power, presence: true
  validates :typee, presence: true

  validate :on => :create do
    errors.add(:base, 'Too many monsters') if self.user.monsters.count >= 20
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user

  validates :monster_1_id, presence: true
  validates :monster_2_id, presence: true
  validates :monster_3_id, presence: true

  validate :on => :create do
    monsters = [self.monster_1_id, self.monster_2_id, self.monster_3_id]
    errors.add(:base, 'Duplicated monsters') if monsters.uniq != monsters
  end

  validate :on => :create do
    errors.add(:base, 'Too many teams') if self.user.teams.count >= 3
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :omniauthable, :omniauth_providers => [:facebook]

  has_many :monsters
  has_many :teams

	def self.new_with_session(params, session)
	  super.tap do |user|
	    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
	      user.email = data["email"] if user.email.blank?
	    end
	  end
	end

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = current_user.monsters.order(params[:sort] || 'name')
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)
    @monster.user_id = current_user.id

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = current_user.monsters.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :power, :typee, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = current_user.teams.all
    @monsters = {}
    @teams.each do |team|
      monster1 = current_user.monsters.find(team.monster_1_id)
      monster2 = current_user.monsters.find(team.monster_2_id)
      monster3 = current_user.monsters.find(team.monster_3_id)
      @monsters[team.id] = [monster1, monster2, monster3]
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @monster1 = current_user.monsters.find(@team.monster_1_id)
    @monster2 = current_user.monsters.find(@team.monster_2_id)
    @monster3 = current_user.monsters.find(@team.monster_3_id)
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)
    @team.user_id = current_user.id

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = current_user.teams.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:monster_1_id, :monster_2_id, :monster_3_id, :user_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper

  def monster_typees
    %w(fire water earth electric wind)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper

  def available_monsters
    current_user.monsters.map{|m| [m.name, m.id]}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<h1>Rubymon</h1>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

    <%= yield %>

		<% unless current_user %>
		  <div><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></div>
		<% else %>
		  <div><%= link_to "Logout", destroy_user_session_path, method: :delete %></div>
		<% end %>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= form_with(model: monster, local: true) do |form| %>
  <% if monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :monster_name %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.text_field :power, id: :monster_power %>
  </div>

	<div class="field">
    <%= form.label :typee %>
		<%= form.select :typee, options_for_select(monster_typees) %>
	</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<h1>Monsters</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Name', :sort => 'name' %></th>
      <th><%= link_to 'Power', :sort => 'power' %></th>
      <th>Type</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.power %></td>
        <td><%= monster.typee %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div><%= link_to 'New Monster', new_monster_path %></div>
<div><%= link_to 'Teams section', teams_path %></div>
<div><%= link_to 'Home page', root_path %></div>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Power:</strong>
  <%= @monster.power %>
</p>

<p>
  <strong>Type:</strong>
  <%= @monster.typee %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>

app/views/pages/home.html.erb
<% if current_user %>
	<div>Logged in as: <%= current_user.name %></div>
	<%= image_tag(current_user.image) %>
	<div><%= link_to 'Monsters section', monsters_path %></div>
<% end %>